# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJXxzQb7QeYYfBqM6whKSzhLt8Kv8xCm
"""

import requests
from bs4 import BeautifulSoup

GOOGLE_SHEET_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbxCStWToKSQmdIBIfJJv9SUsX6-iytcRt1CTePaTga44kgSPDbDpOT1AqMe8BtWbao8/exec"

def scrape_jobs():
    headers = {'User-Agent': 'Mozilla/5.0'}
    url = "https://jobsgovbd.info/"

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    job_cards = soup.find_all('div', class_='bjp-job-card')

    for card in job_cards:
        try:
            title = card.find('h2', class_='job-title').text.strip()
            status = card.find('div', class_='job-status-badge').text.strip()
            category = card.find('div', class_='job-category-badge').text.strip()

            # লোগো URL সংগ্রহ
            logo_img = card.find('img', class_='employer-logo')
            logo_url = logo_img['src'] if logo_img else "N/A"

            dates = card.find_all('div', class_='date-value')
            start_date = dates[0].text.strip() if len(dates) > 0 else "N/A"
            end_date = dates[1].text.strip() if len(dates) > 1 else "N/A"

            # পোস্ট সংখ্যা লজিক
            posts_span = card.find('span', class_='vacancies-value')
            raw_posts = posts_span.text.strip() if posts_span else "0"
            post_number = "নির্ধারিত নয়" if raw_posts == "0" else raw_posts

            apply_link = card.find('a', class_='apply-now-btn')['href']
            detail_link = card.find('a', class_='view-details-btn')['href']

            data = {
                "status": status,
                "category": category,
                "title": title,
                "start_date": start_date,
                "end_date": end_date,
                "post_number": post_number,
                "apply_link": apply_link,
                "detail_link": detail_link,
                "logo_url": logo_url
            }

            requests.post(GOOGLE_SHEET_WEB_APP_URL, json=data)
            print(f"Success: {title}")

        except Exception as e:
            print(f"Error parsing: {e}")

if __name__ == "__main__":
    scrape_jobs()