name: Auto Scraper

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর রান করবে
  workflow_dispatch: # ম্যানুয়ালি টেস্ট করার জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: |
          python main.py
